### PR TITLE
Added new deprication language and removed the documentation erb pages

### PR DESCRIPTION
**Pull request by zachj0hnston**
- Removed the 8 erb pages (no need to document the pages if we are depricating)
- Replaced home page and markdown file with new depreciation message
- Background context: We no longer maintain Scooter at Dropbox and have moved the important CSS insights and variables into our internal front-end framework (DIG)

### CODE REVIEW

**Comment by zachj0hnston** [comment]
@lunaroja can you take a look at this and accept the change. I'll tag you on the internal Phabricator task as well for context.

**Comment by zachj0hnston** [comment]
@lunaroja is there anything I need to do to get these changes reflected into http://dropbox.github.io/scooter/

I see that the Github pages site is still unchanged.

**Comment by zachj0hnston** [comment]
@lunaroja I think I figured it out but need your help running a command since I don't have write permissions on the Scooter codebase.

If you pull down the latest Scooter master branch and run:
```
middleman build
```

Then run:

```
middleman deploy
```
It should publish all this to the Github pages site and finish this all up.

When I try to run that command, I get the following error:

image

**Comment by daneden** [comment]
goodbye

**Comment by zachj0hnston** [comment]
[image: giphy-13.gif]

**Pull request merged**
